serverAddr = "home-frontier.tail4b99b.ts.net"
serverPort = 443

transport.protocol = "wss"

featureGates = { VirtualNet = true }
virtualNet.address = "fe00::1/48"

[[proxies]]
name = "vnet-server"
type = "xtcp"
secretKey = "your-secret-key"
[proxies.plugin]
type = "virtual_net"
